version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli@8.0.6
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - npm install
      - ng build --prod
artifacts:
  files:
    - "**/*"